apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cicd-test
  namespace: default
  annotations:
    filter.fluxcd.io/nginx: semver:~1.1
spec:
  releaseName: cicd-test
  chart:
    git: git@github.com:hwchiu/hiskio-course
    ref: master
    path: cicd/application/helm
  values:
    replicaCount: 1
    nginx:
      image:
        tag: v1.1.9-staging
