---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cicd-test
  namespace: default
  annotations:
    repository.fluxcd.io/nginx: nginx.image.img
    tag.fluxcd.io/nginx: nginx.image.tag
    filter.fluxcd.io/nginx: semver:~2
    fluxcd.io/automated: 'true'
spec:
  releaseName: cicd-test
  chart:
    git: git@github.com:hwchiu/hiskio-course
    ref: sealed
    path: cicd/application/helm
  values:
    nginx:
      image:
        img: hwchiu/cicd-app
        tag: 2.1.1
